import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms for using Toolora in this product preview.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Terms of Service</h1>
      <p className="mt-3 text-sm text-muted">Last updated: sample product preview — for demonstration only.</p>

      <div className="mt-8 space-y-8 text-foreground/80">
        <section>
          <h2 className="text-lg font-semibold text-foreground">Product preview</h2>
          <p className="mt-2 leading-relaxed">
            Toolora, as presented here, is an early-stage MVP built to demonstrate a discovery product
            experience. Tool listings, pricing, ratings and deals shown throughout the site are sample
            data used for illustration and should not be relied on as current or verified information.
          </p>
        </section>
        <section>
          <h2 className="text-lg font-semibold text-foreground">No warranty</h2>
          <p className="mt-2 leading-relaxed">
            Recommendations produced by the Find My Tool questionnaire are generated by a simple,
            deterministic scoring system based on your answers and tool metadata. They are suggestions,
            not professional advice, and should not be the sole basis for a purchasing decision.
          </p>
        </section>
        <section>
          <h2 className="text-lg font-semibold text-foreground">Third-party tools</h2>
          <p className="mt-2 leading-relaxed">
            Toolora links out to third-party products. Your use of any linked tool is governed by that
            provider&apos;s own terms, not Toolora&apos;s.
          </p>
        </section>
      </div>
    </div>
  );
}
